FROM python:3.9.9

WORKDIR /monteCarlo

ADD requirements.txt /monteCarlo/requirements.txt
RUN pip install -r requirements.txt

COPY monteCarloAlgo.py .
COPY logger.py .

CMD ["python", "monteCarloAlgo.py"]