{
 "title": "P6-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(instance)(avg without(cpu) (irate(node_cpu_seconds_total{job=\"integrations/node_exporter\", mode!=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(workload)(count_over_time({application=\"Workload\"}[30m]))",
     "legendFormat": "{{workload}}"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\", namespace=\"\"} [30m])",
     "legendFormat": "Status Monitor"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\", namespace=\"kube-system\"} [30m])",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\", namespace=\"k8s-monitoring\"} [30m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Errors over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({application=\"Workload\", severity=\"error\"} [5m])",
     "legendFormat": "Workload Error"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\"} |= \"FailedScheduling\" |= \"count=1\"[5m])",
     "legendFormat": "Scheduling Error"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\"} |=\"FailedKillPod\" |= \"count=1\"[5m])"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\"} |=\"FailedMount\" |= \"count=1\"[5m])"
    }
   ]
  },
  {
   "title": "Memory Usage over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) ((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/(node_memory_MemTotal_bytes))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance)(avg without(cpu) (irate(node_cpu_seconds_total{job=\"integrations/node_exporter\", mode!=\"idle\"}[5m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Workloads over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\"} |= \"Started container tspapp\"[5m])",
     "legendFormat": "TSP"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\"} |= \"Started container mcapp\"[5m])",
     "legendFormat": "Monte Carlo"
    },
    {
     "expr": "count_over_time({service_name=\"integrations/kubernetes/eventhandler\"} |= \"Started container whisperapp\"[5m])",
     "legendFormat": "Whisper"
    }
   ]
  },
  {
   "title": "Error Cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{service_name=\"integrations/kubernetes/eventhandler\"} |=\"FailedScheduling\" |= \"count=1\""
    },
    {
     "expr": "{service_name=\"integrations/kubernetes/eventhandler\"} |=\"FailedKillPod\" |= \"count=1\""
    },
    {
     "expr": "{service_name=\"integrations/kubernetes/eventhandler\"} |=\"FailedMount\" |= \"count=1\""
    }
   ]
  },
  {
   "title": "Overload Cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{application=\"Workload\"}"
    }
   ]
  },
  {
   "title": "Load Balancing Cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{application=\"Workload\",workload=\"Monte Carlo\", host != \"worker2\"}"
    },
    {
     "expr": "{application=\"Workload\",workload=\"TSP\", host != \"worker1\"}"
    },
    {
     "expr": "{application=\"Workload\",workload=\"Whisper\", host != \"worker3\"}"
    }
   ]
  }
 ]
}