FROM python:3.7
WORKDIR C:\Users\Rasmus\Documents\GitHub\P6-Project
COPY . C:\Users\Rasmus\Documents\GitHub\P6-Project\app
RUN pip install -r requirements.txt
CMD ["python", "./your-daemon-or-script.py"]