apiVersion: apps/v1
kind: pod
metadata: 
  name: whisperWorkload
spec:
  replicas: 1
  selector:
    matchlabels:
      app: p6
  template: 
    metadata: 
      labels:
        app: whisperWorkload
    spec:
      containers:
      - name: container-name
        image: image-name
        ports: 
        - containerPort: 8080
      
